"""Add table Role

Revision ID: 28a839dca61f
Revises: a8af7603f2be
Create Date: 2025-11-15 19:55:30.467991

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a839dca61f'
down_revision = 'a8af7603f2be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes_enderecos',
    sa.Column('id', app.infrastructure.db.types.GUID(), nullable=False),
    sa.Column('cliente_id', app.infrastructure.db.types.GUID(), nullable=False),
    sa.Column('apelido', sa.String(length=120), nullable=True),
    sa.Column('linha1', sa.String(length=255), nullable=False),
    sa.Column('linha2', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=False),
    sa.Column('codigo_postal', sa.String(length=60), nullable=False),
    sa.Column('pais', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', app.infrastructure.db.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_enderecos_tenant_id'), 'clientes_enderecos', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', app.infrastructure.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'clientes', 'clientes_enderecos', ['default_address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_table('roles')
    op.drop_index(op.f('ix_clientes_enderecos_tenant_id'), table_name='clientes_enderecos')
    op.drop_table('clientes_enderecos')
    # ### end Alembic commands ###
