"""descricao

Revision ID: b78512723ba8
Revises: 20240603001
Create Date: 2025-11-13 21:38:35.442421

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b78512723ba8'
down_revision = '20240603001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'status',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'CONCLUIDO', name='agendamentostatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDENTE'::agendamentostatus"))
    op.alter_column('agendamentos', 'metadados_formulario',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('agendamentos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agendamentos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_agendamentos_tenant_id'), 'agendamentos', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('agendamentos_tenant_id_fkey'), 'agendamentos', type_='foreignkey')
    op.create_foreign_key(None, 'agendamentos', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('cart_items', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_cart_items_tenant_id'), 'cart_items', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('cart_items_tenant_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('categorias', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categorias', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_categorias_tenant_id'), 'categorias', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('categorias_tenant_id_fkey'), 'categorias', type_='foreignkey')
    op.create_foreign_key(None, 'categorias', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('clientes', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('clientes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clientes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_clientes_tenant_id'), 'clientes', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('clientes_tenant_id_fkey'), 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('itens_pedido', 'pedido_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('itens_pedido', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('itens_pedido', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('itens_pedido', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_itens_pedido_tenant_id'), 'itens_pedido', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('itens_pedido_tenant_id_fkey'), 'itens_pedido', type_='foreignkey')
    op.create_foreign_key(None, 'itens_pedido', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('merchants', 'avaliacao',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('merchants', 'destaque',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_merchants_tenant_id'), 'merchants', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('merchants_tenant_id_fkey'), 'merchants', type_='foreignkey')
    op.create_foreign_key(None, 'merchants', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('pedidos', 'status',
               existing_type=postgresql.ENUM('CRIADO', 'PENDENTE_PAGAMENTO', 'PAGO', 'CANCELADO', name='pedidostatus'),
               nullable=False,
               existing_server_default=sa.text("'CRIADO'::pedidostatus"))
    op.alter_column('pedidos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pedidos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_pedidos_tenant_id'), 'pedidos', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('pedidos_tenant_id_fkey'), 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('prestadores', 'profissoes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('prestadores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prestadores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_prestadores_tenant_id'), 'prestadores', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('prestadores_tenant_id_fkey'), 'prestadores', type_='foreignkey')
    op.create_foreign_key(None, 'prestadores', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('produtos', 'disponivel',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('produtos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('produtos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_produtos_tenant_id'), 'produtos', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('produtos_tenant_id_fkey'), 'produtos', type_='foreignkey')
    op.create_foreign_key(None, 'produtos', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('servicos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servicos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_servicos_tenant_id'), 'servicos', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('servicos_tenant_id_fkey'), 'servicos', type_='foreignkey')
    op.create_foreign_key(None, 'servicos', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'servicos', type_='foreignkey')
    op.create_foreign_key(op.f('servicos_tenant_id_fkey'), 'servicos', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_servicos_tenant_id'), table_name='servicos')
    op.alter_column('servicos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('servicos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.create_foreign_key(op.f('produtos_tenant_id_fkey'), 'produtos', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_produtos_tenant_id'), table_name='produtos')
    op.alter_column('produtos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('produtos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('produtos', 'disponivel',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'prestadores', type_='foreignkey')
    op.create_foreign_key(op.f('prestadores_tenant_id_fkey'), 'prestadores', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_prestadores_tenant_id'), table_name='prestadores')
    op.alter_column('prestadores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prestadores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prestadores', 'profissoes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('pedidos_tenant_id_fkey'), 'pedidos', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_pedidos_tenant_id'), table_name='pedidos')
    op.alter_column('pedidos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pedidos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pedidos', 'status',
               existing_type=postgresql.ENUM('CRIADO', 'PENDENTE_PAGAMENTO', 'PAGO', 'CANCELADO', name='pedidostatus'),
               nullable=True,
               existing_server_default=sa.text("'CRIADO'::pedidostatus"))
    op.drop_constraint(None, 'merchants', type_='foreignkey')
    op.create_foreign_key(op.f('merchants_tenant_id_fkey'), 'merchants', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_merchants_tenant_id'), table_name='merchants')
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('merchants', 'destaque',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('merchants', 'avaliacao',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    op.create_foreign_key(op.f('itens_pedido_tenant_id_fkey'), 'itens_pedido', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_itens_pedido_tenant_id'), table_name='itens_pedido')
    op.alter_column('itens_pedido', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('itens_pedido', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('itens_pedido', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('itens_pedido', 'pedido_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_tenant_id_fkey'), 'clientes', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_clientes_tenant_id'), table_name='clientes')
    op.alter_column('clientes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clientes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clientes', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'categorias', type_='foreignkey')
    op.create_foreign_key(op.f('categorias_tenant_id_fkey'), 'categorias', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_categorias_tenant_id'), table_name='categorias')
    op.alter_column('categorias', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categorias', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_tenant_id_fkey'), 'cart_items', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_cart_items_tenant_id'), table_name='cart_items')
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.create_foreign_key(op.f('agendamentos_tenant_id_fkey'), 'agendamentos', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_agendamentos_tenant_id'), table_name='agendamentos')
    op.alter_column('agendamentos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agendamentos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agendamentos', 'metadados_formulario',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('agendamentos', 'status',
               existing_type=postgresql.ENUM('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'CONCLUIDO', name='agendamentostatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDENTE'::agendamentostatus"))
    # ### end Alembic commands ###
